services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "website"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
